/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'id' : string, 'items' : Array<CartItem> }
export interface CartItem {
  'id' : string,
  'size' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type Category = { 'men' : null } |
  { 'kids' : null } |
  { 'sale' : null } |
  { 'newArrivals' : null } |
  { 'women' : null };
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'id' : string,
  'size' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : string,
  'featured' : boolean,
  'thumbnail' : ExternalBlob,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface ProductEditDTO {
  'featured' : boolean,
  'thumbnail' : ExternalBlob,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addItemToCart' : ActorMethod<[string, string, bigint], undefined>,
  'addProduct' : ActorMethod<[ProductEditDTO], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllOrders' : ActorMethod<[], Array<[Principal, Array<Order>]>>,
  'listProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'placeOrder' : ActorMethod<[], undefined>,
  'queryProduct' : ActorMethod<[string], Product>,
  'queryProducts' : ActorMethod<[], Array<Product>>,
  'removeItemFromCart' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProductsByName' : ActorMethod<[string], Array<Product>>,
  'updateCartItemQuantity' : ActorMethod<[string, string, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<
    [Principal, string, OrderStatus],
    undefined
  >,
  'updateProduct' : ActorMethod<[string, ProductEditDTO], undefined>,
  'viewOrderHistory' : ActorMethod<[], Array<Order>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];